#ifndef _ASSETLOADER_HPP_
#define _ASSETLOADER_HPP_

// This is an automatically generated file that will load all asset files
// into a map for easy access.

assets.set("Aquatic0", loadImage("assets/Characters/Aquatic0.png", screen));
assets.set("Aquatic1", loadImage("assets/Characters/Aquatic1.png", screen));
assets.set("Avian0", loadImage("assets/Characters/Avian0.png", screen));
assets.set("Avian1", loadImage("assets/Characters/Avian1.png", screen));
assets.set("Cat0", loadImage("assets/Characters/Cat0.png", screen));
assets.set("Cat1", loadImage("assets/Characters/Cat1.png", screen));
assets.set("Demon0", loadImage("assets/Characters/Demon0.png", screen));
assets.set("Demon1", loadImage("assets/Characters/Demon1.png", screen));
assets.set("Dog0", loadImage("assets/Characters/Dog0.png", screen));
assets.set("Dog1", loadImage("assets/Characters/Dog1.png", screen));
assets.set("Elemental0", loadImage("assets/Characters/Elemental0.png", screen));
assets.set("Elemental1", loadImage("assets/Characters/Elemental1.png", screen));
assets.set("Humanoid0", loadImage("assets/Characters/Humanoid0.png", screen));
assets.set("Humanoid1", loadImage("assets/Characters/Humanoid1.png", screen));
assets.set("Misc0", loadImage("assets/Characters/Misc0.png", screen));
assets.set("Misc1", loadImage("assets/Characters/Misc1.png", screen));
assets.set("Pest0", loadImage("assets/Characters/Pest0.png", screen));
assets.set("Pest1", loadImage("assets/Characters/Pest1.png", screen));
assets.set("Plant0", loadImage("assets/Characters/Plant0.png", screen));
assets.set("Plant1", loadImage("assets/Characters/Plant1.png", screen));
assets.set("Player0", loadImage("assets/Characters/Player0.png", screen));
assets.set("Player1", loadImage("assets/Characters/Player1.png", screen));
assets.set("Quadraped0", loadImage("assets/Characters/Quadraped0.png", screen));
assets.set("Quadraped1", loadImage("assets/Characters/Quadraped1.png", screen));
assets.set("Reptile0", loadImage("assets/Characters/Reptile0.png", screen));
assets.set("Reptile1", loadImage("assets/Characters/Reptile1.png", screen));
assets.set("Rodent0", loadImage("assets/Characters/Rodent0.png", screen));
assets.set("Rodent1", loadImage("assets/Characters/Rodent1.png", screen));
assets.set("Slime0", loadImage("assets/Characters/Slime0.png", screen));
assets.set("Slime1", loadImage("assets/Characters/Slime1.png", screen));
assets.set("Undead0", loadImage("assets/Characters/Undead0.png", screen));
assets.set("Undead1", loadImage("assets/Characters/Undead1.png", screen));
assets.set("Engineer Clothes", loadImage("assets/Commissions/Engineer Clothes.png", screen));
assets.set("Engineer", loadImage("assets/Commissions/Engineer.png", screen));
assets.set("Icons", loadImage("assets/Commissions/Icons.png", screen));
assets.set("Mage Clothes", loadImage("assets/Commissions/Mage Clothes.png", screen));
assets.set("Mage", loadImage("assets/Commissions/Mage.png", screen));
assets.set("Paladin Clothes", loadImage("assets/Commissions/Paladin Clothes.png", screen));
assets.set("Paladin", loadImage("assets/Commissions/Paladin.png", screen));
assets.set("Rogue Clothes", loadImage("assets/Commissions/Rogue Clothes.png", screen));
assets.set("Rogue", loadImage("assets/Commissions/Rogue.png", screen));
assets.set("Template", loadImage("assets/Commissions/Template.png", screen));
assets.set("Warrior Clothes Back", loadImage("assets/Commissions/Warrior Clothes Back.png", screen));
assets.set("Warrior Clothes", loadImage("assets/Commissions/Warrior Clothes.png", screen));
assets.set("Warrior", loadImage("assets/Commissions/Warrior.png", screen));
assets.set("GUI0", loadImage("assets/GUI/GUI0.png", screen));
assets.set("GUI1", loadImage("assets/GUI/GUI1.png", screen));
assets.set("Ammo", loadImage("assets/Items/Ammo.png", screen));
assets.set("Amulet", loadImage("assets/Items/Amulet.png", screen));
assets.set("Armor", loadImage("assets/Items/Armor.png", screen));
assets.set("Book", loadImage("assets/Items/Book.png", screen));
assets.set("Boot", loadImage("assets/Items/Boot.png", screen));
assets.set("Chest0", loadImage("assets/Items/Chest0.png", screen));
assets.set("Chest1", loadImage("assets/Items/Chest1.png", screen));
assets.set("Flesh", loadImage("assets/Items/Flesh.png", screen));
assets.set("Food", loadImage("assets/Items/Food.png", screen));
assets.set("Glove", loadImage("assets/Items/Glove.png", screen));
assets.set("Hat", loadImage("assets/Items/Hat.png", screen));
assets.set("Key", loadImage("assets/Items/Key.png", screen));
assets.set("Light", loadImage("assets/Items/Light.png", screen));
assets.set("LongWep", loadImage("assets/Items/LongWep.png", screen));
assets.set("MedWep", loadImage("assets/Items/MedWep.png", screen));
assets.set("Money", loadImage("assets/Items/Money.png", screen));
assets.set("Music", loadImage("assets/Items/Music.png", screen));
assets.set("Potion", loadImage("assets/Items/Potion.png", screen));
assets.set("Ring", loadImage("assets/Items/Ring.png", screen));
assets.set("Rock", loadImage("assets/Items/Rock.png", screen));
assets.set("Scroll", loadImage("assets/Items/Scroll.png", screen));
assets.set("Shield", loadImage("assets/Items/Shield.png", screen));
assets.set("ShortWep", loadImage("assets/Items/ShortWep.png", screen));
assets.set("Tool", loadImage("assets/Items/Tool.png", screen));
assets.set("Wand", loadImage("assets/Items/Wand.png", screen));
assets.set("Decor0", loadImage("assets/Objects/Decor0.png", screen));
assets.set("Decor1", loadImage("assets/Objects/Decor1.png", screen));
assets.set("Door0", loadImage("assets/Objects/Door0.png", screen));
assets.set("Door1", loadImage("assets/Objects/Door1.png", screen));
assets.set("Effect0", loadImage("assets/Objects/Effect0.png", screen));
assets.set("Effect1", loadImage("assets/Objects/Effect1.png", screen));
assets.set("Fence", loadImage("assets/Objects/Fence.png", screen));
assets.set("Floor", loadImage("assets/Objects/Floor.png", screen));
assets.set("Ground0", loadImage("assets/Objects/Ground0.png", screen));
assets.set("Ground1", loadImage("assets/Objects/Ground1.png", screen));
assets.set("Hill0", loadImage("assets/Objects/Hill0.png", screen));
assets.set("Hill1", loadImage("assets/Objects/Hill1.png", screen));
assets.set("Map0", loadImage("assets/Objects/Map0.png", screen));
assets.set("Map1", loadImage("assets/Objects/Map1.png", screen));
assets.set("Ore0", loadImage("assets/Objects/Ore0.png", screen));
assets.set("Ore1", loadImage("assets/Objects/Ore1.png", screen));
assets.set("Pit0", loadImage("assets/Objects/Pit0.png", screen));
assets.set("Pit1", loadImage("assets/Objects/Pit1.png", screen));
assets.set("Tile", loadImage("assets/Objects/Tile.png", screen));
assets.set("Trap0", loadImage("assets/Objects/Trap0.png", screen));
assets.set("Trap1", loadImage("assets/Objects/Trap1.png", screen));
assets.set("Tree0", loadImage("assets/Objects/Tree0.png", screen));
assets.set("Tree1", loadImage("assets/Objects/Tree1.png", screen));
assets.set("Wall", loadImage("assets/Objects/Wall.png", screen));

#endif // _ASSETLOADER_HPP_